import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(process.env.JORNADA_RUNTIME_PACKAGE||import.meta.url);const {chromium}=require('playwright');
const [packagePath,outputPath,...flags]=process.argv.slice(2);if(!packagePath||!outputPath)throw Error('Informe pacote e saída.');
const live=flags.includes('--live');
const mime={'.html':'text/html; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.ico':'image/x-icon'};
const server=http.createServer(async(req,res)=>{let name=new URL(req.url,'http://local').pathname.replace(/^\/tea\//,'');if(!name)name='index.html';if(name.includes('..')||name==='peca-jornada.webp'){res.writeHead(404);return res.end();}try{const raw=await fs.readFile(path.join(packagePath,name));res.writeHead(200,{'Content-Type':mime[path.extname(name)]||'application/octet-stream'});res.end(raw);}catch{res.writeHead(404);res.end();}});
if(!live)await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));await fs.mkdir(outputPath,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'});const url=live?'https://hub.unimedgv.com/tea/':`http://127.0.0.1:${server.address().port}/tea/`;const report={mode:live?'produção real':'local',url,allPassed:false,results:[]};
try{for(const width of [320,390,768,1440]){const context=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));let writes=0,mapRequests=0,telemetry=0;page.on('request',r=>{if(!['GET','HEAD'].includes(r.method())){const target=new URL(r.url());if(target.pathname==='/cdn-cgi/rum')telemetry++;else writes++;}if(r.url().includes('peca-jornada.webp'))mapRequests++;});
await page.goto(url,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>{for(const image of document.images)image.loading='eager';});await page.waitForFunction(()=>[...document.images].filter(i=>!i.closest('#gate')).every(i=>i.complete),null,{timeout:15000});
assert.equal(await page.locator('.jornada-convite').count(),1);assert.equal(await page.locator('img[src*="peca-jornada"]').count(),0);
const proof=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,images:[...document.images].filter(i=>!i.closest('#gate')).every(i=>i.complete&&i.naturalWidth>0),jornada:document.querySelector('.p2').getAttribute('href'),painel:document.querySelector('.p3').getAttribute('href'),reportRole:document.querySelector('#porta-rel').getAttribute('role')}));
assert(proof.scroll<=proof.width+1);assert(proof.images);assert.equal(proof.jornada,'https://open.grupocsv.com/jornada-tea/');assert.equal(proof.painel,'https://hub.grupocsv.com/p/painel-tea/');assert.equal(proof.reportRole,'button');
await page.locator('.p2').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(outputPath,`hub-jornada-${width}.png`),animations:'disabled'});
await page.locator('#porta-rel').click();await page.locator('#gate').waitFor({state:'visible'});await page.locator('#gate-email').waitFor({state:'visible'});await page.locator('#gate-x').click();assert.equal(await page.locator('#gate').isVisible(),false);
assert.equal(writes,0);assert.equal(mapRequests,0);assert.deepEqual(errors,[]);report.results.push({width,passed:true,noMapRequest:true,reportModalPreserved:true,telemetryRequests:telemetry,applicationWrites:writes,proof});await context.close();}
report.allPassed=true;
}catch(error){report.failure=String(error);process.exitCode=1;}finally{await browser.close();if(!live)await new Promise(resolve=>server.close(resolve));await fs.writeFile(path.join(outputPath,'browser-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}
